n1=input('Digite qualquer valor\n')
print('Qual tipo pertence?',type(n1))
print('É apenas espaço?',n1.isspace())
print('É apenas alfabético?',n1.isalpha())
print('É apenas numérico?',n1.isnumeric())
print('É alfanumérico?',n1.isalnum())
print('Esta maiusculo?',n1.isupper())
print('Esta minúsculo?',n1.islower())
print('Esta capitalizado?',n1.istitle())