valor=input('Digite algo\n')
print('O tipo primitivo desse valor eh',type(valor))
print('So tem espacos?',valor.isspace())
print('E apenas numero?',valor.isnumeric())
print('E apenas alfabetico?',valor.isalpha())
print('E alfanumerico?',valor.isalnum())
print('E Totalmente maiusculo?',valor.isupper())
print('E Totalmente minusculo?',valor.islower())
print('Esta capitalizado',valor.istitle())